apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: commshub
  description: Communication Hub
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
  tags:
    - java
    - springboot
    - microservice
  annotations:
    backstage.io/techdocs-ref: dir:.
    # jenkins.io/job-full-name: VF_IOT_MANAGED_CONNECTIVITY/MICROSERVICES/MicroApps_CommHub
    github.com/project-slug: RRIOTDEMO/CommsHub
    sonarqube.org/project-key: RRIOTDEMO_CommsHub_AYRsuJQx5O9cwmTDcT4c
spec:
  type: service
  lifecycle: production
  owner: enablers
  system: comms
  dependsOn: ['resource:commshub-db','component:jms']
  consumesApis:
    - jms-api
  
