apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: commshub
  description: Communication Hub
  tags:
    - java
    - springboot
    - microservice
  annotations:
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: VF_IOT_MANAGED_CONNECTIVITY/MICROSERVICES/MicroApps_CommHub
spec:
  type: service
  lifecycle: production
  owner: enablers
  system: comms
  dependsOn: ['resource:commshub-db','component:jms']
  consumesApis:
    - jms-api
  
